blog/urls.py
from django.urls import include, path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='home'),
    #path('addTodo/', addTodo),
    #path('deleteTodo/<int:todo_id',deleteTodo),
]

mysite/blog/urls.py
from django.urls import include, path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    #path('addTodo/', addTodo),
    #path('deleteTodo/<int:todo_id',deleteTodo),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('blog/', include('blog.urls')),
    path('', include('blog.urls')),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('blog/', include('blog.urls')),
]

todos/urls.py
from django.urls import include, path
from . import views

app_name = "todos"

urlpatterns = [
    path('', views.home, name='home'),
    #path('addTodo/', addTodo),
    #path('deleteTodo/<int:todo_id',deleteTodo),
]

blog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now())
    published_date = models.DateTimeField(
        blank=True, null=True
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

todos/models.py
from django.db import models


# Create your models here.
class TodoItem(models.Model):
    content = models.TextField()


class List(models.Model):
    item = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.item + ' | ' + str(self.completed)

todos/forms.py
from django import forms
from .models import List

class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['item', 'completed']

blog/views.py
from django.shortcuts import render

# Create your views here.

def post_list(request):
    return render(request, 'blog/post_list.html', {})

mysite/blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

# Create your views here.

def post_list(request):
    post = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

todos/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import TodoItem
from .models import List
from .forms import ListForm
from django.contrib import messages


# Create your views here.

# def witam(request):
#    return HttpResponse("Witam")

def todoView(request):
    all_todo_items = TodoItem.objets.all()
    return render(request, 'todos/todo.html',
                  {'all_items': all_todo_items})


def addTodo(request):
    new_item = TodoItem(content=request.POST['content'])
    new_item.save()
    return HttpResponseRedirect('todos')


def deleteTodo(request, todo_id):
    item_to_delete = TodoItem.objects.get(id=todo_id)
    item_to_delete.delete()
    return HttpResponseRedirect('/todos/')


def home(request):
    if request.method == 'POST':
        form = ListForm(request.POST)

        if form.is_valid():
            form.save()
            all_items = List.objects.all
            messages.success(request, 'Item Has Been Added To List!')
            return render(request, 'todos/home.html', {'all_items': all_items})
        return HttpResponse('cos nie pykło')
    else:
        all_items = List.objects.all
        return render(request, 'todos/home.html', {'all_items': all_items})

mysite/blog/templates/blog/post_list.html
<html>
    <head>
        <title>Django Girls blog</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>

        <div>
            <p>published: 14.06.2014, 12:14</p>
            <h2><a href="">My first post</a></h2>
            <p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        </div>

        <div>
            <p>published: 14.06.2014, 12:14</p>
            <h2><a href="">My second post</a></h2>
            <p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut f.</p>
        </div>
        <div>
            <p>published: 14.06.2040, 12:14</p>
            <h2><a href="">My third post</a></h2>
            <p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut f.</p>
        </div>

    </body>
</html>

todos/templates/todos/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'todos:home' %}">To-Do List</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">



        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Add Item" aria-label="Search">
          <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add To List</button>
        </form>
      </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/home.html
{% extends 'todos/base.html' %}

{% block content %}
   {% if messages %}
   {% for message in messages %}
       <div class="alert alert-warning alert-dismissable" role="alert">
           <button class="close" data-dismiss="alert">
               <small><sup>x</sup></small>
           </button>
           {{ message }}
       </div>
   {% endfor %}
{% endif %}

{% if all_items %}
    {% for things in all_items %}
        {{ things.item }} | {{ things.completed }}
    {% endfor %}
{% endif %}

{% endblock %}

todos/templates/todos/todo.html
<h1>this is the todo page.</h1>
<h1>christos anesti</h1>
<ul>
    <li>temporary todo item A</li>
    <li>temporary todo item B</li>
</ul>

<ul>
    {% for todo_item in all_items %}
      <li>{{ todo_item.content }}
          <form action="/deleteTodo/{{todo_item.id}}"
                style="display: inline;"
                method="post">{% csrf_token %}
             <input type="submit" value="Delete"/>
          </form>
      </li>
    {% endfor %}
</ul>

<form action="/addTodo/" method="post">{% csrf_token %}
    <input type="text" name="content"/>
    <input type="submit" value="Add"/>
</form>